@startuml
!include plantuml.conf
start
:Пользователь или офицер\nсоздает заявку (CSR или серверная генерация);
:Проверка профиля/политики\n(EKU, DN, срок);
if (Профиль допустим?) then (да)
  if (Серверная генерация?) then (да)
    :Генерация ключа + сертификата;
    :Формирование PKCS#12\n(с паролем);
  else (нет)
    :Подписание CSR\nсертификатом CA;
  endif
  :Сохранение метаданных в БД;
  :Публикация цепочки/CRL при необходимости;
  :Запись события в аудит;
  :Доставка артефактов\n(PEM/PKCS#12/цепочка);
else (нет)
  :Отклонение заявки\n(лог/аудит);
endif
stop
@enduml
